### PR TITLE
Fixed regex bug, entry handling before extraction and empty lorebook message

### LINKED ISSUE #51: Lorebook entries are always present in context
## Summary
Lore entries are a way of giving the AI context on places, characters and details of a the story it's telling, creating a "world" for it to describe when the entries are mentioned. But only when they're mentioned.

## Details
Entries are always in the context, which means they're being pulled from the database even when they're not mentioned. This not only clogs the context with unnecessary tokens, but could also cause leaks and break of format since the items in the entries are not being talked about in the current story/chat context.

### Expected behavior
Given that a user has a lorebook entry called "John Doe", when that entry is mentioned by its regex tag, then it should be pulled from the DB and added into the top of the AI's memory context.

### Actual behavior
Entries are always pulled into the context regardless of mentions of their regex tag. This clogs up context and adds risk of leaking and adding info of items that are not there in the current point of its context, and also wastes available tokens leading to more expensive bills on API usage.

### PR DESCRIPTION
**Pull request by thaalesalves**

### CODE REVIEW

File: src/main/java/es/thalesalv/gptbot/application/service/commands/CreateLorebookEntryService.java [hunk 1]
```diff
@@ -145,7 +146,9 @@ private LorebookRegex insertEntry(final User author, final String entryName, fin
 
         return lorebookRegexRepository.save(LorebookRegex.builder()
                 .id(lorebookRegexId)
-                .regex(Optional.ofNullable(entryRegex).orElse(entryName))
+                .regex(Optional.ofNullable(entryRegex)
+                        .filter(StringUtils::isNotBlank)
+                        .orElse(entryName))
```
Comment (MagicShel) [inline src/main/java/es/thalesalv/gptbot/application/service/commands/CreateLorebookEntryService.java:151]: I wonder if we should just store character name as the regex if it's blank. But this is cool, too.

**Review by MagicShel — APPROVED** [review]

File: src/main/java/es/thalesalv/gptbot/application/service/commands/CreateLorebookEntryService.java (hunk 1 above)
Comment (thaalesalves) [reply src/main/java/es/thalesalv/gptbot/application/service/commands/CreateLorebookEntryService.java:151]: But that's exactly what is being done there. Tries to store regex and it's empty stores the name instead
